# Generated by Django 4.2.6 on 2023-10-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energyaudit",
            name="devices",
        ),
        migrations.RemoveField(
            model_name="energyaudit",
            name="operation_hours",
        ),
        migrations.CreateModel(
            name="DeviceAuditData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_hours", models.FloatField()),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.energyaudit",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.energydevice",
                    ),
                ),
            ],
        ),
    ]
