# Generated by Django 4.2.6 on 2023-10-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_remove_energyaudit_devices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyaudit",
            name="devices",
            field=models.ManyToManyField(to="audit.energydevice"),
        ),
        migrations.AddField(
            model_name="energyaudit",
            name="operation_hours",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="DeviceAuditData",
        ),
    ]
